[tools]
python = "3.12"
node = "22"


[tasks.db-up]
run = 'docker compose up -d --wait'

[tasks.electric-up]
run = "docker compose up -d electric"


[tasks.migrate]
depends = ['db-up']
run = 'cd backend && uv run manage.py migrate'


[tasks.api]
depends = ['migrate']
run = 'cd backend && granian --interface asginl core.asgi:application'


[tasks.dev-client]
run = 'cd frontend && pnpm --color run dev'


[tasks.dev]
depends = ['api', 'dev-client']



[env]

# PostgreSQL 
POSTGRES_USER = 'postgres'
POSTGRES_PASSWORD = 'postgres'
POSTGRES_DB = 'postgres'
POSTGRES_PORT = 5433
POSTGRES_HOST = 'localhost'

# Electric 
ELECTRIC_PORT = 5133
ELECTRIC_URL = 'ws://localhost:${ELECTRIC_PORT}'
ELECTRIC_AUTH_JWT_ALG = 'HS256'
ELECTRIC_AUTH_JWT_KEY = 'SUPER_SECRET_JWT_KEY_CHANGE_ME'
ELECTRIC_INSECURE = true

# Django
ALLOWED_HOSTS = 'localhost 127.0.0.1 [::1]' 
DJANGO_DEBUG = 1 
DJANGO_SECRET_KEY = 'SECRET_KEY'


# Granian
GRANIAN_RELOAD = 0
GRANIAN_RELOAD_IGNORE_PATTERNS = '(?<!\.py)$'
GRANIAN_PORT = 8000 
GRANIAN_WORKERS = 1 

# Python
PYTHONUNBUFFERED = 1







